obs_collection=gaia_dr3
hats_primary_table_url=s3://stpubdata/gaia/gaia_dr3/public/hats/gaia
all_margins=https://data.lsdb.io/hats/gaia_dr3/gaia_10arcs https://data.lsdb.io/hats/gaia_dr3/gaia_300arcs
default_margin=https://data.lsdb.io/hats/gaia_dr3/gaia_10arcs
all_indexes=source_id https://data.lsdb.io/hats/gaia_dr3/gaia_source_id_index