services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --address ":9000" --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_API_SELECT_PARQUET: on
    volumes:
      - ./minio_data:/data
    ports:
      - "127.0.0.1:9001:9001"
      - "127.0.0.1:9000:9000"

volumes:
  minio_data:
