services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --address ":9000" --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio_data:/data
    ports:
      - "127.0.0.1:9001:9001"
    networks:
      - minio_network

  nginx:
    image: nginx:latest
    container_name: minio_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "127.0.0.1:9000:80"
    depends_on:
      - minio
    networks:
      - minio_network

volumes:
  minio_data:

networks:
  minio_network:
    driver: bridge
